[package]
name = "example_instancing_test"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "example_instancing_test_desktop"
path = "src/main.rs"

[lib]
name = "example_instancing_test"
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]

[dependencies]
orbital = { path = "../../Runtime" }
