[package]
name = "orbital_ecs"
version = "0.1.0"
edition = "2024"

[[bench]]
name = "ecs_bench"
harness = false

[dependencies]
rayon = { workspace = true }

[target.'cfg(target_arch = "wasm32")'.dependencies]
wasm-bindgen-rayon = { workspace = true, optional = true }

[features]
default = []
wasm-threads = ["wasm-bindgen-rayon"]

[dev-dependencies]
rand = { workspace = true }
criterion = { workspace = true }
