[workspace]
resolver = "2"
members = ["Examples/*", "Crates/*"]

[workspace.dependencies]
wgpu = { version = "30.0.0", features = [
    "angle",
    "dx12",
    "glsl",
    "metal",
    "naga-ir",
    "serde",
    "spirv",
    "webgl",
    "webgpu",
    "wgsl",
] }
cgmath = "0.18.0"
dirs = "6.0.0"
gltf = { version = "1.4.1", features = ["KHR_lights_punctual"] }
fern = "0.7.0"
hashbrown = "0.17.0"
humantime = "2.1.0"
image = "0.25.0"
log = "0.4.21"
rand = "0.10.0"
serde = { version = "1.0.174", features = ["derive"] }
ulid = "1.1.0"
winit = "0.30.0"
glob = "0.3.1"
gilrs = "0.11.0"
android_logger = "0.15.0"
pollster = "0.4"
rayon = "1.10"
wasm-bindgen-rayon = "1.2"
criterion = { version = "0.8", features = ["html_reports"] }

[profile.release]
lto = true
opt-level = 3
codegen-units = 1
incremental = false
debug = false

[profile.dev]
opt-level = 1
lto = "thin"
codegen-units = 16

[profile.dev.package.wgpu]
opt-level = 3

[profile.dev.package.winit]
opt-level = 3

[profile.dev.package.hashbrown]
opt-level = 3

[profile.dev.package.cgmath]
opt-level = 3
