name: Main
on:
  workflow_dispatch:
  pull_request:
  push:
    tags:
      - 'v*'
permissions:
  contents: write
env:
  CARGO_TERM_COLOR: always
jobs:
  clippy:
    runs-on: linux
    steps:
      - name: ⏬ Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      - name: 💾 Cache
        uses: actions/cache@v5.0.1
        with:
          path: target/
          key: target
      - name: 🦀 Rust setup
        run: |
          rustup default stable
          rustup update
      - name: 📎 Clippy
        env:
          SKIP_GLTF_EXPORT: true
        run: cargo clippy
  rustfmt:
    runs-on: linux
    steps:
      - name: ⏬ Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      - name: 💾 Cache
        uses: actions/cache@v5.0.1
        with:
          path: target/
          key: target
      - name: 🦀 Rust setup
        run: |
          rustup default stable
          rustup update
      - name: 🧹 RustFmt
        env:
          SKIP_GLTF_EXPORT: true
        run: cargo fmt --all --check
  check:
    runs-on: linux
    needs:
      - rustfmt
      - clippy
    steps:
      - name: ⏬ Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      - name: 💾 Cache
        uses: actions/cache@v5.0.1
        with:
          path: target/
          key: target
      - name: 🦀 Rust setup
        run: |
          rustup default stable
          rustup update
      - name: 🔍 Check
        env:
          SKIP_GLTF_EXPORT: true
        run: cargo check
  test:
    runs-on: linux
    steps:
      - name: ⏬ Checkout
        uses: actions/checkout@v6
        with:
          ref: ${{ github.head_ref }}
      - name: 💾 Cache
        uses: actions/cache@v5.0.1
        with:
          path: target/
          key: target
      - name: 🦀 Rust setup
        run: |
          rustup default stable
          rustup update
      - name: 🧪 Test
        run: cargo test
  build:
    runs-on: linux
    needs:
      - check
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: ⏬ Checkout
        uses: actions/checkout@v6
      - name: 💾 Cache
        uses: actions/cache@v5.0.1
        with:
          path: target/
          key: target-${{ matrix.target }}
      - name: 🦀 Rust setup
        run: |
          rustup default stable
          rustup update
      - name: ➕ Make upload folder
        run: mkdir upload
      - name: 🔎 Find files to upload
        run: |
          find target/${{ matrix.target }}/release -mindepth 1 -maxdepth 1 -type f -not -name '*.d' -not -name '*.rlib' -not -name '.cargo-lock' -not -name 'CACHEDIR.TAG' -exec mv {} upload/ \;
          mv Assets/ upload/
      - name: 📦 Make archive
        working-directory: upload
        run: zip -r ../${{ matrix.target }}.zip .
      - name: ⬆️ Upload artifacts
        uses: actions/upload-artifact@v6
        with:
          name: ${{ matrix.target }}
          path: ${{ matrix.target }}.zip
          if-no-files-found: 'error'
  release:
    runs-on: linux
    needs:
      - build
      - test
    if: ${{ startsWith(github.ref, 'refs/tags/') }}
    steps:
      - name: ⬇️ Download artifacts from this run
        uses: actions/download-artifact@v7
      - name: ➕ Make upload folder
        run: mkdir upload
      - name: 🔄 Move files to upload folder
        run: find . -type f -name '*.zip' -exec mv {} upload/ \;
      - name: 👀 Show files to be uploaded
        run: ls -al upload/
      - name: 📝 Make release
        uses: actions/forgejo-release@v2
        with:
          direction: upload
          release-dir: upload/
          release-notes-assistant: true
