[package]
name = "world_change"
version = "0.1.0"
edition = "2024"

[dependencies]
app = { workspace = true }
camera = { workspace = true }
message = { workspace = true }
model = { workspace = true }
log = { workspace = true }
wgpu = { workspace = true }
