[package]
name = "orbital_app"
version = "0.1.0"
edition = "2024"

[features]
gamepad_input = ["dep:gilrs"]
auto_request_redraw = []
gamepad_input_poll = ["gamepad_input"]
default = []

[dependencies]
orbital_core = { path = "../orbital_core" }
orbital_ecs = { path = "../ecs" }
orbital_ecs_bridge = { path = "../orbital_ecs_bridge" }
orbital_input = { path = "../orbital_input" }
orbital_renderer = { path = "../orbital_renderer" }
orbital_resources = { path = "../orbital_resources" }
cgmath = { workspace = true }
log = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }

gilrs = { workspace = true, optional = true }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = { workspace = true }
winit = { workspace = true, features = ["android-native-activity"] }
