// Generated by `wit-bindgen` 0.53.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     orbital:core@0.1.0

package orbital_core_commands

import ()

const (
	CommandRegisterSystem uint8 = 0
)

type Command struct {
	tag   uint8
	value any
}

func (self Command) Tag() uint8 {
	return self.tag
}

func (self Command) RegisterSystem() string {
	if self.tag != CommandRegisterSystem {
		panic("tag mismatch")
	}
	return self.value.(string)
}

func MakeCommandRegisterSystem(value string) Command {
	return Command{CommandRegisterSystem, value}
}

type CommandBuffer struct {
	Commands []Command
}
