[package]
name = "DamagedHelmet"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "example_damaged_helmet_desktop"
path = "src/lib.rs"

[lib]
name = "example_damaged_helmet_android"
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]

[dependencies]
orbital = { path = "../../Runtime" }