[package]
name = "orbital_importer_gltf"
version = "0.1.0"
edition = "2024"

[dependencies]
orbital_core = { path = "../orbital_core" }
orbital_camera = { path = "../orbital_camera" }
orbital_light = { path = "../orbital_light" }
orbital_material_shader = { path = "../orbital_material_shader" }
orbital_mesh = { path = "../orbital_mesh" }
orbital_model = { path = "../orbital_model" }
orbital_shader_pbr = { path = "../orbital_shader_pbr" }
orbital_texture = { path = "../orbital_texture" }
orbital_math = { path = "../orbital_math" }
orbital_file_manager = { path = "../orbital_file_manager" }
cgmath = { workspace = true }
gltf = { workspace = true }
hashbrown = { workspace = true }
log = { workspace = true }
ulid = { workspace = true }
wgpu = { workspace = true }
rayon = { workspace = true }
image = { workspace = true }
base64 = "0.22"
urlencoding = "2.1"

[dev-dependencies]
serde_json = "1"
