[package]
name = "orbital_importer_gltf"
version = "0.1.0"
edition = "2024"

[dependencies]
orbital_core = { path = "../orbital_core" }
orbital_resources = { path = "../orbital_resources" }
orbital_file_manager = { path = "../orbital_file_manager" }
cgmath = { workspace = true }
gltf = { workspace = true }
hashbrown = { workspace = true }
log = { workspace = true }
ulid = { workspace = true }
wgpu = { workspace = true }
rayon = { workspace = true }
image = { workspace = true }
base64 = "0.23"
urlencoding = "2.1"

[dev-dependencies]
serde_json = "1"
