[package]
name = "texture_realization"
version = "0.1.0"
edition = "2024"

[dependencies]
texture_descriptor = { path = "../texture_descriptor/" }

wgpu = { workspace = true }
cgmath = {workspace = true }
image = {workspace = true }
