[package]
name = "test-roll-camera"
version = "0.1.0"
edition = "2024"

[lib]
name = "test_roll_camera"
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]

[[bin]]
name = "test-roll-camera"
path = "src/main.rs"

[dependencies]
orbital = { path = "../../Crates/orbital" }
winit = { workspace = true }
