[package]
name = "wgpu_test_adapter"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = { workspace = true }
smol = { workspace = true }
logging = { workspace = true }
log = { workspace = true }
