[package]
name = "PBRSpheres"
version = "0.1.0"
edition = "2024"

[[bin]]
name = "example_pbr_spheres_desktop"
path = "src/lib.rs"

[lib]
name = "example_pbr_spheres_android"
path = "src/lib.rs"
crate-type = ["cdylib", "lib"]

[dependencies]
orbital = { path = "../../Runtime" }