// Generated by `wit-bindgen` 0.53.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     orbital:core@0.1.0

package orbital_core_module

import (
	"wit_component/orbital_core_commands"
)

type CommandBuffer = orbital_core_commands.CommandBuffer
