FROM {{CROSS_BASE_IMAGE}}

# Install libudev-dev
RUN apt-get update && \
    apt-get install -y --no-install-recommends libudev-dev blender python3-numpy libdraco-dev draco mesa-utils && \
    rm -rf /var/lib/apt/lists/*
