[package]
name = "orbital_element"
version = "0.1.0"
edition = "2021"

[dependencies]
orbital_input = { path = "../orbital_input" }
orbital_core = { path = "../orbital_core" }
orbital_resources = { path = "../orbital_resources" }
orbital_importer_gltf = { path = "../orbital_importer_gltf" }
log = { workspace = true }
hashbrown = { workspace = true }
serde = { workspace = true }
winit = { workspace = true }
