[package]
name = "orbital_ecs_bridge"
version = "0.1.0"
edition = "2024"

[dependencies]
orbital_core = { path = "../orbital_core" }
orbital_ecs = { path = "../ecs" }
orbital_importer_gltf = { path = "../orbital_importer_gltf" }
orbital_resources = { path = "../orbital_resources" }
cgmath = { workspace = true }
hashbrown = { workspace = true }
orbital_input = { path = "../orbital_input" }
ulid = { workspace = true }
wgpu = { workspace = true }
