[package]
name = "orbital_model"
version = "0.1.0"
edition = "2024"

[dependencies]
orbital_core = { path = "../orbital_core" }
orbital_mesh = { path = "../orbital_mesh" }
orbital_instance = { path = "../orbital_instance" }
orbital_math = { path = "../orbital_math" }
orbital_material_shader = { path = "../orbital_material_shader" }
hashbrown = { workspace = true }
ulid = { workspace = true }
wgpu = { workspace = true }
