[package]
name = "ibl_brdf"
version = "0.1.0"
edition = "2024"

[dependencies]
wgpu = { workspace = true }
texture = { workspace = true }
logging = { workspace = true }
wgpu_test_adapter = { workspace = true }
cgmath = { workspace = true }
