[package]
name = "orbital_debug_render"
version = "0.1.0"
edition = "2021"

[dependencies]
cgmath = { workspace = true }
wgpu = { workspace = true }
winit = { workspace = true }

orbital_app = { path = "../orbital_app" }
orbital_camera = { path = "../orbital_camera" }
orbital_ecs = { path = "../ecs" }
orbital_ecs_bridge = { path = "../orbital_ecs_bridge" }
orbital_light = { path = "../orbital_light" }
