// Generated by `wit-bindgen` 0.53.0. DO NOT EDIT!
//
// This code was generated from the following packages:
//     orbital:core@0.1.0

package main

import (
	"github.com/bytecodealliance/wit-bindgen/wit_runtime"
	"github.com/bytecodealliance/wit-bindgen/wit_types"
	"runtime"
	"unsafe"
	"wit_component/export_orbital_core_module"
	"wit_component/orbital_core_commands"
)

var staticPinner = runtime.Pinner{}
var exportReturnArea = uintptr(wit_runtime.Allocate(&staticPinner, (3 * 4), 4))
var syncExportPinner = runtime.Pinner{}

//go:wasmexport orbital:core/module@0.1.0#startup
func wasm_export_orbital_core_module_startup() uintptr {

	pinner := &syncExportPinner
	result := export_orbital_core_module.Startup()

	switch result.Tag() {
	case wit_types.OptionNone:
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(0))

	case wit_types.OptionSome:
		payload := result.Some()
		*(*int8)(unsafe.Add(unsafe.Pointer(exportReturnArea), 0)) = int8(int32(1))
		slice := (payload).Commands
		length := uint32(len(slice))
		result0 := wit_runtime.Allocate(pinner, uintptr(length*(3*4)), 4)
		for index, element := range slice {
			base := unsafe.Add(result0, index*(3*4))

			switch element.Tag() {
			case orbital_core_commands.CommandRegisterSystem:
				payload := element.RegisterSystem()
				*(*int8)(unsafe.Add(unsafe.Pointer(base), 0)) = int8(int32(0))
				utf8 := unsafe.Pointer(unsafe.StringData(payload))
				pinner.Pin(utf8)
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), (2 * 4))) = uint32(uint32(len(payload)))
				*(*uint32)(unsafe.Add(unsafe.Pointer(base), 4)) = uint32(uintptr(uintptr(utf8)))

			default:
				panic("unreachable")
			}

		}

		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), (2 * 4))) = uint32(length)
		*(*uint32)(unsafe.Add(unsafe.Pointer(exportReturnArea), 4)) = uint32(uintptr(uintptr(result0)))

	default:
		panic("unreachable")
	}
	return exportReturnArea

}

//go:wasmexport cabi_post_orbital:core/module@0.1.0#startup
func wasm_export_post_return_orbital_core_module_startup(result uintptr) {
	syncExportPinner.Unpin()
}

// Unused, but present to make the compiler happy
func main() {}
