[package]
name = "orbital"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["lib", "cdylib"]

[features]
default = ["gamepad_input", "gamepad_input_poll", "auto_request_redraw"]
renderdoc = []
# Enables gamepad inputs from being polled and processed.
gamepad_input = ["dep:gilrs", "orbital_input/gamepad_input", "orbital_app/gamepad_input"]
# Automatically polls gamepad inputs and processes them.
gamepad_input_poll = ["gamepad_input", "orbital_app/gamepad_input_poll"]
# Will automatically request a redraw when the last frame was rendered.
auto_request_redraw = ["orbital_app/auto_request_redraw"]

[build-dependencies]
glob = { workspace = true }

[dependencies]
orbital_core = { path = "../orbital_core" }
orbital_input = { path = "../orbital_input" }
orbital_shader_preprocessor = { path = "../orbital_shader_preprocessor" }
orbital_resources = { path = "../orbital_resources" }
orbital_importer_gltf = { path = "../orbital_importer_gltf" }
wgpu = { workspace = true }
cgmath = { workspace = true }
dirs = { workspace = true }
gltf = { workspace = true }
hashbrown = { workspace = true }
image = { workspace = true }
log = { workspace = true }
rand = { workspace = true }
serde = { workspace = true }
ulid = { workspace = true }
winit = { workspace = true }
glob = { workspace = true }
rayon = { workspace = true }

orbital_renderer = { path = "../orbital_renderer" }
orbital_app = { path = "../orbital_app" }
orbital_ecs = { path = "../ecs" }
orbital_ecs_bridge = { path = "../orbital_ecs_bridge" }
orbital_debug_render = { path = "../orbital_debug_render" }

gilrs = { workspace = true, optional = true }

[target.'cfg(target_os = "android")'.dependencies]
android_logger = { workspace = true }
winit = { workspace = true, features = ["android-native-activity"] }
