depends_on: [linting]

when:
  - event: manual
  - event: pull_request

steps:
  restore_cache:
    image: forgejo.sakul-flee.de/sakulflee/orbital-ci-build-image:latest
    pull: true
    volumes:
      - /var/lib/woodpecker/cache:/cache:rw
    commands:
      - mkdir -p /cache/orbital/target /cache/orbital/cargo
      - rsync -a /cache/orbital/target/ target/ || true
      - rsync -a /cache/orbital/cargo/ /usr/local/cargo/ || true

  test:
    image: forgejo.sakul-flee.de/sakulflee/orbital-ci-build-image:latest
    pull: true
    environment:
      SKIP_GLTF_EXPORT: "true"
    commands:
      - cargo test --no-fail-fast

  save_cache:
    image: forgejo.sakul-flee.de/sakulflee/orbital-ci-build-image:latest
    pull: true
    volumes:
      - /var/lib/woodpecker/cache:/cache:rw
    commands:
      - rsync -a --delete target/ /cache/orbital/target/
      - rsync -a /usr/local/cargo/registry/ /cache/orbital/cargo/registry/
      - rsync -a /usr/local/cargo/git/ /cache/orbital/cargo/git/
