when:
  - event: manual
  - event: pull_request

steps:
  test:
    image: nixos/nix:latest
    environment:
      SKIP_GLTF_EXPORT: "true"
    commands:
      - nix develop --extra-experimental-features 'nix-command flakes' --command cargo test --no-fail-fast
