name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Cache
      uses: actions/cache@v4.1.1
      with:
        path: target/
        key: target

    - run: sudo apt-get install -y libudev-dev
    
    - name: Clippy
      run: cargo clippy --workspace --all-targets --all-features -- -W clippy::all
      continue-on-error: true
      
    - name: Tests
      run: cargo test --workspace
      continue-on-error: true
